version: "3.7"
services:
  webapp:
    build: .
    ports: 
      - "8100:80"
  db:
    image: wangxian/alpine-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"