version: "3.7"
services:
  webapp:
    build: .
    restart: on-failure
    ports: 
      - "${WEBAPP_PORT}"
    environment:
      SERVER: ${SERVER}
      DB_NAME: ${MYSQL_DATABASE}
      USERNAME: ${MYSQL_USER}
      PASS: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
  mysql:
    image: wangxian/alpine-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d