version: "3.7"
services:
  php:
    container_name: php
    build:
        context: ./docker/php
    ports:
        - ${PHP_PORT}
    volumes:
        - ./src/:/srv/www/api
        - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      SERVER: ${MYSQL_CONTAINER_NAME}
      DB_NAME: ${MYSQL_DATABASE}
      USERNAME: ${MYSQL_USER}
      PASS: ${MYSQL_PASSWORD}
  nginx:
    container_name: nginx
    image: nginx:1.17.9-alpine
    ports:
        - ${NGINX_PORT}
    volumes:
        - ./src/:/srv/www/api
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
volumes:
  db_data: